# Generated by Django 4.2.13 on 2024-06-17 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_item_image_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Similar_Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('picture_link', models.URLField(default='Unknown')),
                ('price', models.CharField(max_length=200)),
                ('link', models.URLField(default='Unknown')),
                ('original_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.item')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['store', 'item_name'],
            },
        ),
    ]
