# Generated by Django 4.2.13 on 2024-06-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_item_options_item_item_id_similar_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similar_item',
            name='original_item_id',
            field=models.IntegerField(default=0),
        ),
    ]
